### ISSUE TITLE
assuming memo is of high cardinality and should not be in Prometheus

### ISSUE THREAD

**Issue by dzmitry-lahoda** [informalsystems/chainpulse#5]
also signer is also high, it it may be not so variable as memo (assuming memo can be anything)
afaik prometheus generally dislikes high cardinality data.

cardinality of cartesian product without memo already huge btw.

**Comment by romac** [comment]
From what we are seeing on the channels we've monitored so far, there is almost a 1:1 mapping between signer and memo and therefore removing the memo would not decrease the cardinality that much. I agree we could still do without the memo and map signers to memo somewhere else than in the Prometheus metrics, but it hasn't cause any issue for us so far and has proved valuable to quickly identify how each relayer software/operator is performing.

Are you seeing any issues yourself with this?

**Comment by dzmitry-lahoda** [comment]
i am doing research on how memo is used or to be used (on top of just relayer note).

it feels parsing specific memo formats and making labels is the way to go.

`here is almost a 1:1 mapping between signer and memo` <- parse signer and put into metrics

as soon as somebody will want more specific fields from specific memo usage - he will PR here.

https://github.com/ComposableFi/composable/pull/3647

https://github.com/cosmos/ibc/pull/976

(and we are going to use to invoke arbitrary CW contracts).

**Comment by dzmitry-lahoda** [comment]
not sure so that relayers memo are of any meaning. there should be offchain relayer register which allows map tx senders to relayers.

**Comment by dzmitry-lahoda** [comment]
just remove memo and if you wish parse info from it.
